version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=mydatabase
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    container_name: mariadb_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wwmnot
    volumes:
      - db_data:/var/lib/mysql
      - ./wwmnot.sql:/docker-entrypoint-initdb.d/wwmnot.sql
    ports:
      - '3306:3306'

volumes:
  db_data:
